package com.bjdx.dao;

import com.bjdx.pojo.ClassInfo;
import com.bjdx.pojo.ClassInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int countByExample(ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int deleteByExample(ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int deleteByPrimaryKey(String classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int insert(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int insertSelective(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    List<ClassInfo> selectByExample(ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    ClassInfo selectByPrimaryKey(String classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ClassInfo record, @Param("example") ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int updateByExample(@Param("record") ClassInfo record, @Param("example") ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int updateByPrimaryKeySelective(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    int updateByPrimaryKey(ClassInfo record);
}