package com.bjdx.pojo;

public class ClassInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classinfo.class_id
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classinfo.class_name
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classinfo.type_id
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    private String typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classinfo.class_id
     *
     * @return the value of classinfo.class_id
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classinfo.class_id
     *
     * @param classId the value for classinfo.class_id
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classinfo.class_name
     *
     * @return the value of classinfo.class_name
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classinfo.class_name
     *
     * @param className the value for classinfo.class_name
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classinfo.type_id
     *
     * @return the value of classinfo.type_id
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classinfo.type_id
     *
     * @param typeId the value for classinfo.type_id
     *
     * @mbggenerated Mon Mar 12 13:43:45 CST 2018
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
}